kind: Deployment
apiVersion: apps/v1
metadata:
  name: dvwa2
spec:
  template:
    metadata:
      labels:
        app: dvwa2
    spec:
      containers:
      - name: dvwa2
        image: public.ecr.aws/f9n2h3p5/dvwapub:<TAG>
        imagePullPolicy: "Always"
  selector:
    matchLabels:
      app: dvwa2
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa2
spec:
  type: LoadBalancer
  selector:
    app: dvwa2
  ports:
  - name: http
    port: 8081
    targetPort: 80
